import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@repo/ui/globals.css';
import { NavigationMenu } from "repo/ui/components/navigation-menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Satisfactory Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavigationMenu>
          
        </NavigationMenu>
        {children}
      </body>
    </html>
  );
}
